# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

impl_zstdCompress <- function(object, level) {
    .Call('_zstdR_impl_zstdCompress', PACKAGE = 'zstdR', object, level)
}

impl_zstdUncompress <- function(raw) {
    .Call('_zstdR_impl_zstdUncompress', PACKAGE = 'zstdR', raw)
}

